### ISSUE TITLE
feature: add support for type checking the generated project

### ISSUE THREAD

**Issue by mikavilpas** [S1M0N38/galileo.nvim#4]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

> As a developer, I see the lua language server report type errors when I am working with lua. However, these errors are not checked in CI.
> I want to make sure my project (and contributor PRs) are free from type errors, so that it's easier for everyone to work on the code.

### Describe the solution you'd like

There is a github action for this here https://github.com/mrcjkb/lua-typecheck-action. I haven't tried it out myself (yet).

It looks like it was published 1 year ago here https://www.reddit.com/r/neovim/comments/10fmag4/plugin_devs_type_check_your_lua_plugins_with/

### Describe alternatives you've considered

-

### Additional context

Here are some considerations:

- It might be a feature some people don't want to have.
- It might even be a feature some people don't use or want.
- It might require instructions on how to add/manage dependencies.

**Comment by S1M0N38** [comment]
Implemented in 1.0.0
