### ISSUE TITLE
feature: consider using selene instead of luacheck for linting

### ISSUE THREAD

**Issue by mikavilpas** [S1M0N38/galileo.nvim#5]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Someone pointed out luacheck might be falling out of date to me here https://github.com/gsuuon/tshjkl.nvim/pull/10#pullrequestreview-1833965956

I was able to add the [selene lua linter](https://kampfkarren.github.io/selene/selene.html) in its place very easily. I think this might be a good alternative to consider, as a sort of recommendation for the community.

### Describe the solution you'd like

- Add a selene command in the Makefile along with minimal configuration for vim apis and testing. These can be found in the PR above as examples.
- Add selene as a github action. This is also done in the PR above.

### Describe alternatives you've considered

-

### Additional context

There is a detailed comparison between the two linters available here https://kampfkarren.github.io/selene/luacheck.html

**Comment by S1M0N38** [comment]
In 1.0.0 I opted for using just lua language server. For linting, typechecking and formatting.
